#!/usr/bin/env python3
"""
Send interview prep DOCX to Boss's work email.
Usage: python3 send_email.py <candidate_name> <filepath>
"""
import smtplib
import sys
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import os

GMAIL_USER = "yonghuatrc@gmail.com"
GMAIL_APP_PASSWORD=os.environ.get("SMTP_PASSWORD", "")
TO_EMAIL = "dennis_ng@nuhs.edu.sg"

def send(candidate_name, docx_path, batch_id, score, additional_info=""):
    safe_name = candidate_name.replace(" ", "_")
    filename = os.path.basename(docx_path)

    msg = MIMEMultipart()
    msg["From"] = GMAIL_USER
    msg["To"] = TO_EMAIL
    msg["Subject"] = f"Interview Prep — {candidate_name}"

    body = f"""Hi Boss,

Please find attached the Interview Preparation document for {candidate_name}.

Source: ResumeScanner (Batch {batch_id})
ResumeScanner Score: {score}/100

This document includes:
- Candidate summary & scoring
- Flag signals (HIRE / NO-HIRE)
- Section 1: Accountability & Responsibility (STAR-format questions)
- Section 2: Technical — Epic, NGEMR, IT Project Stages
- Scoring rubric & decision guide

{additional_info}

Generated by Hermes InterviewGenerator.

Best,
Hermes Agent"""

    msg.attach(MIMEText(body, "plain"))

    with open(docx_path, "rb") as f:
        part = MIMEBase("application", "octet-stream")
        part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header("Content-Disposition", f"attachment; filename={filename}")
        msg.attach(part)

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
        server.send_message(msg)

    print(f"SUCCESS: Emailed to {TO_EMAIL}")

if __name__ == "__main__":
    if len(sys.argv) < 5:
        print("Usage: send_email.py <candidate_name> <docx_path> <batch_id> <score>")
        sys.exit(1)
    send(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
